mobile_detect:
    redirect:
        full:
            action: redirect            # redirect, no_redirect, redirect_without_path
            host: '%env(REDIRECT_DESKTOP)%'
            is_enabled: true            # default false
            status_code: 301            # default 302
        mobile:
            action: redirect            # redirect, no_redirect, redirect_without_path
            host: '%env(REDIRECT_MOBILE)%'     # with scheme (http|https), default null, url validate
            is_enabled: true           # default false
            status_code: 301            # default 302
        tablet:
            action: redirect            # redirect, no_redirect, redirect_without_path
            host: '%env(REDIRECT_TABLET)%'    # with scheme (http|https), default null, url validate
            is_enabled: true          # default false
            status_code: 301            # default 302

    switch_device_view:
        save_referer_path: true                  # default true
        # true  redirectUrl = http://site.com/current/path?currentQuery=string
      # false redirectUrl = http://site.com
    cookie_expire_datetime_modifier: '+1 hour' # default
    cookie_key: 'device_view'                   # default
    switch_param: 'device_view'                 # default